# File: .github/workflows/test-runner.yml
#
# Purpose: This workflow runs tests for Node.js, Python, C#, and a Logic App.
# It uses a self-hosted runner on Linux (ARM64) to execute these tests.

name: Test Runner (Node, Python, C# & Logic App)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-node:
    runs-on: [self-hosted, Linux]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Run hello-world.js
        run: node tests/node/hello-world.js

  test-python:
    runs-on: [self-hosted, Linux]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run Python Hello World
        run: python3 tests/python/hello-world.py

  test-csharp:
    runs-on: [self-hosted, Linux]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Verify .NET SDK installation
        run: |
          dotnet --version
          if [ $? -ne 0 ]; then
            echo "Error: .NET SDK is not properly installed or configured."
            exit 1
          fi

      - name: Restore dependencies
        run: dotnet restore tests/csharp/HelloWorld.csproj

      - name: Build project
        run: dotnet build tests/csharp/HelloWorld.csproj --configuration Release --no-restore

      - name: Run tests
        run: dotnet test tests/csharp/HelloWorld.csproj --configuration Release --no-build --verbosity normal

      - name: Run project
        run: dotnet run --project tests/csharp/HelloWorld.csproj --configuration Release --no-build

  test-logic-app:
    runs-on: [self-hosted, Linux]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Azure Functions Core Tools
        run: |
          sudo npm install -g azure-functions-core-tools@4
          echo "PATH=$PATH:/home/github-runner/.npm-global/bin" >> $GITHUB_ENV
          source $GITHUB_ENV
          func --version

      - name: Setup Logic App project
        run: |
          mkdir -p tests/logicapp/workflow
          cp tests/logicapp/workflow.json tests/logicapp/workflow/
          echo '{"IsEncrypted":false,"Values":{"AzureWebJobsStorage":"UseDevelopmentStorage=true","FUNCTIONS_WORKER_RUNTIME":"node"}}' > tests/logicapp/workflow/local.settings.json

      - name: Start Logic App
        run: |
          cd tests/logicapp/workflow
          func start --javascript &
          sleep 30

      - name: Test Logic App
        run: |
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:7071/api/workflow_trigger)
          if [ $RESPONSE -eq 200 ]; then
            echo "Logic App test passed"
          else
            echo "Logic App test failed"
            exit 1
          fi

      - name: Cleanup
        if: always()
        run: pkill -f "func start"