# File: .github/workflows/main-workflow.yml

name: Main Test Runner

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-node:
    uses: ./.github/workflows/test-node.yml

  test-python:
    uses: ./.github/workflows/test-python.yml

  test-csharp:
    uses: ./.github/workflows/test-csharp.yml

  test-logic-app:
    uses: ./.github/workflows/test-logicapp.yml