name: Test Runner (Node, Python & C#)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-node:
    runs-on: [self-hosted, Linux]
    steps:
        - uses: actions/checkout@v4
        - name: Use Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '20'
        - name: Run hello-world.js
          run: node tests/node/hello-world.js

  test-python:
    runs-on: [self-hosted, Linux]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run Python Hello World
        run: python3 tests/python/hello-world.py

  test-csharp:
    runs-on: [self-hosted, Linux]
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        
        - name: Install .NET SDK
          run: |
            # Download .NET SDK
            wget https://dot.net/v1/dotnet-install.sh
            chmod +x dotnet-install.sh
            ./dotnet-install.sh --channel 8.0 --install-dir $HOME/.dotnet
            
            # Add .NET to PATH
            echo "$HOME/.dotnet" >> $GITHUB_PATH
            echo "DOTNET_ROOT=$HOME/.dotnet" >> $GITHUB_ENV

        - name: Compile and Run C# Hello World
          run: |
            dotnet new console -o tests/csharp -n HelloWorld
            cp tests/csharp/hello-world.cs tests/csharp/Program.cs
            dotnet run --project tests/csharp