name: Logic App Test

on:
  workflow_call:

jobs:
  test-logicapp:
    runs-on: [self-hosted, Linux, ARM64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          echo "PATH=$PATH:/home/github-runner/.npm-global/bin" >> $GITHUB_ENV
          . ~/.bashrc

      - name: Verify Azure Functions Core Tools installation
        run: |
          which func
          func --version

      - name: Start Logic App
        run: |
          cd tests/logicapp
          func start --javascript &
          sleep 30

      - name: Test Logic App
        run: |
          RESPONSE=$(curl -s http://localhost:7071/api/workflow_trigger)
          echo "Response: $RESPONSE"
          if [[ "$RESPONSE" == *"Hello, Logic App World!"* ]]; then
            echo "Logic App test passed"
            exit 0
          else
            echo "Logic App test failed"
            exit 1
          fi

      - name: Cleanup
        if: always()
        run: pkill -f "func start" || true