# File: .github/workflows/test-runner-node.yml
#
# Purpose: This workflow tests the GitHub Actions runner by running a simple Node.js program.
# It demonstrates that the runner is correctly set up and can execute Node.js jobs.

name: Test Runner (Node.js)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-runner-node:
    runs-on: [self-hosted, Linux]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    - name: Run hello-world.js
      run: node tests/node/hello-world.js